version: 0.0
os: linux
files:
  #TODO ASPNETCORE_CONFIGURATION 에 따른 source path 설정 
  - source: Api/bin/release/netcoreapp3.1/
    destination: /home/ubuntu/aspnetcoreservice
  - source: scripts/virtualhost.conf
    destination: /home/ubuntu/aspnetcoreservice
  - source: scripts/kestrel-aspnetcoreservice.service
    destination: /etc/systemd/system
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dotnetcore
      timeout: 500
      runas: root

    - location: scripts/install_httpd
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root
