#!/bin/bash
cd /home/ubuntu/

# install dotnet core
# https://www.microsoft.com/net/core#linuxubuntu
if [ ! -f /usr/bin/dotnet ]; then
    apt-get install libunwind8
                  
    wget https://download.visualstudio.microsoft.com/download/pr/d731f991-8e68-4c7c-8ea0-fad5605b077a/49497b5420eecbd905158d86d738af64/dotnet-sdk-3.1.100-linux-x64.tar.gz -P /opt/dotnet/ \
    && sha512sum -c <<< "5217ae1441089a71103694be8dd5bb3437680f00e263ad28317665d819a92338a27466e7d7a2b1f6b74367dd314128db345fa8fff6e90d0c966dea7a9a43bd21 /opt/dotnet/dotnet-sdk-3.1.100-linux-x64.tar.gz" \
    && tar -xvzf /opt/dotnet/dotnet-sdk-3.1.100-linux-x64.tar.gz -C /opt/dotnet/ \
    && ln -sf /opt/dotnet/dotnet /usr/bin/dotnet \
    && rm /opt/dotnet/dotnet-sdk-3.1.100-linux-x64.tar.gz
fi

# first time running dotnet tool requires setting up package cache
dotnet nuget
