//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already deleted..
        /// </summary>
        internal static string Already_deleted_ {
            get {
                return ResourceManager.GetString("Already deleted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists email..
        /// </summary>
        internal static string Already_exists_email_ {
            get {
                return ResourceManager.GetString("Already exists email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists name..
        /// </summary>
        internal static string Already_exists_name_ {
            get {
                return ResourceManager.GetString("Already exists name.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists phoneNumber..
        /// </summary>
        internal static string Already_exists_phone_number_ {
            get {
                return ResourceManager.GetString("Already exists phone number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppUuid is null or empty..
        /// </summary>
        internal static string AppUuid_is_null_or_empty_ {
            get {
                return ResourceManager.GetString("AppUuid is null or empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find parent comment..
        /// </summary>
        internal static string Can_t_find_parent_comment_ {
            get {
                return ResourceManager.GetString("Can\'t find parent comment.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t self follow..
        /// </summary>
        internal static string Can_t_self_follow_ {
            get {
                return ResourceManager.GetString("Can\'t self follow.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send SMS to phone number..
        /// </summary>
        internal static string Can_t_send_SMS_to_phone_number_ {
            get {
                return ResourceManager.GetString("Can\'t send SMS to phone number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous underscore is not allowed..
        /// </summary>
        internal static string Continuous_underscore_is_not_allowed_ {
            get {
                return ResourceManager.GetString("Continuous underscore is not allowed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect..
        /// </summary>
        internal static string Current_password_is_incorrect_ {
            get {
                return ResourceManager.GetString("Current password is incorrect.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either &apos;Email&apos; or &apos;PhoneNumber&apos; must not be empty..
        /// </summary>
        internal static string Either__Email__or__PhoneNumber__must_not_be_empty_ {
            get {
                return ResourceManager.GetString("Either \'Email\' or \'PhoneNumber\' must not be empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address not valid..
        /// </summary>
        internal static string Email_address_not_valid_ {
            get {
                return ResourceManager.GetString("Email address not valid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not attached..
        /// </summary>
        internal static string File_not_attached_ {
            get {
                return ResourceManager.GetString("File not attached.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between {0} and {1} characters long..
        /// </summary>
        internal static string Must_be_between__0__and__1__characters_long_ {
            get {
                return ResourceManager.GetString("Must be between {0} and {1} characters long.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be string..
        /// </summary>
        internal static string Must_be_string_ {
            get {
                return ResourceManager.GetString("Must be string.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must use at least one alphabet and underscore..
        /// </summary>
        internal static string Must_use_at_least_one_alphabet_and_underscore_ {
            get {
                return ResourceManager.GetString("Must use at least one alphabet and underscore.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not exist comment..
        /// </summary>
        internal static string Not_exist_comment_ {
            get {
                return ResourceManager.GetString("Not exist comment.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not exist user or password incorrect..
        /// </summary>
        internal static string Not_exist_user_or_password_incorrect_ {
            get {
                return ResourceManager.GetString("Not exist user or password incorrect.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not exists person..
        /// </summary>
        internal static string Not_exists_person_ {
            get {
                return ResourceManager.GetString("Not exists person.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not exists shot..
        /// </summary>
        internal static string Not_exists_shot_ {
            get {
                return ResourceManager.GetString("Not exists shot.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported image format({0})..
        /// </summary>
        internal static string Not_supported_image_format__0___ {
            get {
                return ResourceManager.GetString("Not supported image format({0}).", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not verified..
        /// </summary>
        internal static string Not_verified_ {
            get {
                return ResourceManager.GetString("Not verified.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only lowercase alphanumeric or underscore characters(a-z,0-9,_) allowed..
        /// </summary>
        internal static string Only_lowercase_alphanumeric_or_underscore_characters_a_z_0_9____allowed_ {
            get {
                return ResourceManager.GetString("Only lowercase alphanumeric or underscore characters(a-z,0-9,_) allowed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number not valid..
        /// </summary>
        internal static string Phone_number_not_valid_ {
            get {
                return ResourceManager.GetString("Phone number not valid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request was temporarily blocked due to a large number of confirmation requests. Please try again later..
        /// </summary>
        internal static string Request_was_temporarily_blocked_due_to_a_large_number_of_confirmation_requests__Please_try_again_later_ {
            get {
                return ResourceManager.GetString("Request was temporarily blocked due to a large number of confirmation requests. P" +
                        "lease try again later.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag not matched then files..
        /// </summary>
        internal static string Tag_not_matched_then_files_ {
            get {
                return ResourceManager.GetString("Tag not matched then files.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid uuid..
        /// </summary>
        internal static string The__0__field_is_not_a_valid_uuid_ {
            get {
                return ResourceManager.GetString("The {0} field is not a valid uuid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        internal static string The__0__field_is_required_ {
            get {
                return ResourceManager.GetString("The {0} field is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be alphanumeric(a-z,A-Z,0-9)..
        /// </summary>
        internal static string The__0__field_must_be_alphanumeric_ {
            get {
                return ResourceManager.GetString("The {0} field must be alphanumeric.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be upper alphanumeric(A-Z,0-9)..
        /// </summary>
        internal static string The__0__field_must_be_upper_alphanumeric_ {
            get {
                return ResourceManager.GetString("The {0} field must be upper alphanumeric.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is already used..
        /// </summary>
        internal static string The__0__is_already_used_ {
            get {
                return ResourceManager.GetString("The {0} is already used.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not exist..
        /// </summary>
        internal static string The__0__is_not_exist_ {
            get {
                return ResourceManager.GetString("The {0} is not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is not in E164 format.
        /// </summary>
        internal static string The__0__is_not_in_E164_format_ {
            get {
                return ResourceManager.GetString("The {0} is not in E164 format.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The aspect ratio of the attached photo is not supported..
        /// </summary>
        internal static string The_aspect_ratio_of_the_attached_photo_is_not_supported_ {
            get {
                return ResourceManager.GetString("The aspect ratio of the attached photo is not supported.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can be changed once every {0} days. (Last changed at {1}).
        /// </summary>
        internal static string The_name_can_be_changed_once_every__0__days___Last_changed_at__1__ {
            get {
                return ResourceManager.GetString("The name can be changed once every {0} days. (Last changed at {1})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name you want to change is the same as before..
        /// </summary>
        internal static string The_name_you_want_to_change_is_the_same_as_before_ {
            get {
                return ResourceManager.GetString("The name you want to change is the same as before.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification information is wrong..
        /// </summary>
        internal static string The_verification_information_is_wrong_ {
            get {
                return ResourceManager.GetString("The verification information is wrong.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no verification history..
        /// </summary>
        internal static string There_is_no_verification_history_ {
            get {
                return ResourceManager.GetString("There is no verification history.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        internal static string User_does_not_exist_ {
            get {
                return ResourceManager.GetString("User does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string User_not_found_ {
            get {
                return ResourceManager.GetString("User not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code is not the same..
        /// </summary>
        internal static string Verification_Code_is_not_the_same_ {
            get {
                return ResourceManager.GetString("Verification Code is not the same.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification has expired. Please verificate again..
        /// </summary>
        internal static string Verification_has_expired__Please_verificate_again_ {
            get {
                return ResourceManager.GetString("Verification has expired. Please verificate again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification request info is not match..
        /// </summary>
        internal static string Verification_request_info_is_not_match_ {
            get {
                return ResourceManager.GetString("Verification request info is not match.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification request not exists..
        /// </summary>
        internal static string Verification_request_not_exists_ {
            get {
                return ResourceManager.GetString("Verification request not exists.", resourceCulture);
            }
        }
    }
}
