//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ko {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ko() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Properties.Resources.ko", typeof(Resources_ko).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 삭제되었습니다..
        /// </summary>
        internal static string Already_deleted_ {
            get {
                return ResourceManager.GetString("Already deleted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 존재하는 이메일입니다..
        /// </summary>
        internal static string Already_exists_email_ {
            get {
                return ResourceManager.GetString("Already exists email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 존재하는 이름입니다..
        /// </summary>
        internal static string Already_exists_name_ {
            get {
                return ResourceManager.GetString("Already exists name.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 존재하는 전화 번호입니다..
        /// </summary>
        internal static string Already_exists_phone_number_ {
            get {
                return ResourceManager.GetString("Already exists phone number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppUuid가 null이거나 비어 있습니다..
        /// </summary>
        internal static string AppUuid_is_null_or_empty_ {
            get {
                return ResourceManager.GetString("AppUuid is null or empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 부모 댓글을 찾을 수 없습니다..
        /// </summary>
        internal static string Can_t_find_parent_comment_ {
            get {
                return ResourceManager.GetString("Can\'t find parent comment.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 스스로 팔로우할 수 없습니다..
        /// </summary>
        internal static string Can_t_self_follow_ {
            get {
                return ResourceManager.GetString("Can\'t self follow.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전화 번호로 SMS를 보낼 수 없습니다..
        /// </summary>
        internal static string Can_t_send_SMS_to_phone_number_ {
            get {
                return ResourceManager.GetString("Can\'t send SMS to phone number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연속 밑줄은 허용되지 않습니다..
        /// </summary>
        internal static string Continuous_underscore_is_not_allowed_ {
            get {
                return ResourceManager.GetString("Continuous underscore is not allowed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 암호가 맞지 않습니다..
        /// </summary>
        internal static string Current_password_is_incorrect_ {
            get {
                return ResourceManager.GetString("Current password is incorrect.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;이메일&apos;또는 &apos;전화번호&apos;는 비워 둘 수 없습니다..
        /// </summary>
        internal static string Either__Email__or__PhoneNumber__must_not_be_empty_ {
            get {
                return ResourceManager.GetString("Either \'Email\' or \'PhoneNumber\' must not be empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이메일 주소가 유효하지 않습니다..
        /// </summary>
        internal static string Email_address_not_valid_ {
            get {
                return ResourceManager.GetString("Email address not valid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파일이 첨부되지 않았습니다..
        /// </summary>
        internal static string File_not_attached_ {
            get {
                return ResourceManager.GetString("File not attached.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ~ {1} 자 사이 여야합니다..
        /// </summary>
        internal static string Must_be_between__0__and__1__characters_long_ {
            get {
                return ResourceManager.GetString("Must be between {0} and {1} characters long.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문자열이어야합니다..
        /// </summary>
        internal static string Must_be_string_ {
            get {
                return ResourceManager.GetString("Must be string.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 하나 이상의 알파벳과 밑줄을 사용해야합니다..
        /// </summary>
        internal static string Must_use_at_least_one_alphabet_and_underscore_ {
            get {
                return ResourceManager.GetString("Must use at least one alphabet and underscore.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 존재하지 않은 댓글입니다..
        /// </summary>
        internal static string Not_exist_comment_ {
            get {
                return ResourceManager.GetString("Not exist comment.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 존재하지 않는 사용자 또는 비밀번호가 올바르지 않습니다..
        /// </summary>
        internal static string Not_exist_user_or_password_incorrect_ {
            get {
                return ResourceManager.GetString("Not exist user or password incorrect.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 존재하지 않는 사람입니다..
        /// </summary>
        internal static string Not_exists_person_ {
            get {
                return ResourceManager.GetString("Not exists person.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 존재하지 않는 샷입니다..
        /// </summary>
        internal static string Not_exists_shot_ {
            get {
                return ResourceManager.GetString("Not exists shot.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 지원되지 않는 이미지 형식 ({0})입니다..
        /// </summary>
        internal static string Not_supported_image_format__0___ {
            get {
                return ResourceManager.GetString("Not supported image format({0}).", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인되지 않았습니다..
        /// </summary>
        internal static string Not_verified_ {
            get {
                return ResourceManager.GetString("Not verified.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 소문자 영숫자 또는 밑줄 문자 (a-z, 0-9, _) 만 허용됩니다..
        /// </summary>
        internal static string Only_lowercase_alphanumeric_or_underscore_characters_a_z_0_9____allowed_ {
            get {
                return ResourceManager.GetString("Only lowercase alphanumeric or underscore characters(a-z,0-9,_) allowed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 전화 번호가 유효하지 않습니다..
        /// </summary>
        internal static string Phone_number_not_valid_ {
            get {
                return ResourceManager.GetString("Phone number not valid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인 요청이 많아 요청이 일시적으로 차단되었습니다. 나중에 다시 시도하십시오..
        /// </summary>
        internal static string Request_was_temporarily_blocked_due_to_a_large_number_of_confirmation_requests__Please_try_again_later_ {
            get {
                return ResourceManager.GetString("Request was temporarily blocked due to a large number of confirmation requests. P" +
                        "lease try again later.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 태그와 파일이 일치하지 않습니다..
        /// </summary>
        internal static string Tag_not_matched_then_files_ {
            get {
                return ResourceManager.GetString("Tag not matched then files.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 필드는 유효한 uuid가 아닙니다..
        /// </summary>
        internal static string The__0__field_is_not_a_valid_uuid_ {
            get {
                return ResourceManager.GetString("The {0} field is not a valid uuid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 필드는 필수입니다..
        /// </summary>
        internal static string The__0__field_is_required_ {
            get {
                return ResourceManager.GetString("The {0} field is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 필드는 영숫자(a-z,A-Z,0-9) 여야합니다..
        /// </summary>
        internal static string The__0__field_must_be_alphanumeric_ {
            get {
                return ResourceManager.GetString("The {0} field must be alphanumeric.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 필드는 대문자 영문 또는 숫자(A-Z,0-9) 여야합니다..
        /// </summary>
        internal static string The__0__field_must_be_upper_alphanumeric_ {
            get {
                return ResourceManager.GetString("The {0} field must be upper alphanumeric.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}은 (는) 이미 사용 중입니다..
        /// </summary>
        internal static string The__0__is_already_used_ {
            get {
                return ResourceManager.GetString("The {0} is already used.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}이 (가) 존재하지 않습니다..
        /// </summary>
        internal static string The__0__is_not_exist_ {
            get {
                return ResourceManager.GetString("The {0} is not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}는 E164 형식이 아닙니다..
        /// </summary>
        internal static string The__0__is_not_in_E164_format_ {
            get {
                return ResourceManager.GetString("The {0} is not in E164 format.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 첨부 된 사진의 화면비는 지원되지 않습니다..
        /// </summary>
        internal static string The_aspect_ratio_of_the_attached_photo_is_not_supported_ {
            get {
                return ResourceManager.GetString("The aspect ratio of the attached photo is not supported.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이름은 {0} 일에 한 번 변경할 수 있습니다. ({1}에 마지막으로 변경됨).
        /// </summary>
        internal static string The_name_can_be_changed_once_every__0__days___Last_changed_at__1__ {
            get {
                return ResourceManager.GetString("The name can be changed once every {0} days. (Last changed at {1})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 변경하려는 이름은 이전과 동일합니다..
        /// </summary>
        internal static string The_name_you_want_to_change_is_the_same_as_before_ {
            get {
                return ResourceManager.GetString("The name you want to change is the same as before.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인 정보가 잘못되었습니다..
        /// </summary>
        internal static string The_verification_information_is_wrong_ {
            get {
                return ResourceManager.GetString("The verification information is wrong.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인 내역이 없습니다..
        /// </summary>
        internal static string There_is_no_verification_history_ {
            get {
                return ResourceManager.GetString("There is no verification history.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용자가 존재하지 않습니다..
        /// </summary>
        internal static string User_does_not_exist_ {
            get {
                return ResourceManager.GetString("User does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 사용자를 찾을 수 없습니다..
        /// </summary>
        internal static string User_not_found_ {
            get {
                return ResourceManager.GetString("User not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인 코드가 동일하지 않습니다..
        /// </summary>
        internal static string Verification_Code_is_not_the_same_ {
            get {
                return ResourceManager.GetString("Verification Code is not the same.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인이 만료되었습니다. 다시 확인하십시오..
        /// </summary>
        internal static string Verification_has_expired__Please_verificate_again_ {
            get {
                return ResourceManager.GetString("Verification has expired. Please verificate again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인 요청 정보가 일치하지 않습니다..
        /// </summary>
        internal static string Verification_request_info_is_not_match_ {
            get {
                return ResourceManager.GetString("Verification request info is not match.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인 요청이 없습니다..
        /// </summary>
        internal static string Verification_request_not_exists_ {
            get {
                return ResourceManager.GetString("Verification request not exists.", resourceCulture);
            }
        }
    }
}
